# Generated by Django 3.1.7 on 2021-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210406_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imdage',
            field=models.ImageField(default='defult.png', upload_to='new'),
        ),
    ]
