# Generated by Django 3.1.7 on 2021-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210407_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imdage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
