# Generated by Django 3.1.7 on 2021-04-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210407_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imdage',
            new_name='image',
        ),
    ]
